from app.api.routers import (
    auth,
    backups,
    console,
    content,
    dashboard,
    files,
    java_profiles,
    modpacks,
    provisioning,
    schedules,
    security_events,
    servers,
    server_templates,
    system_status,
    users,
)

__all__ = [
    "auth",
    "backups",
    "console",
    "content",
    "dashboard",
    "files",
    "java_profiles",
    "modpacks",
    "provisioning",
    "schedules",
    "security_events",
    "servers",
    "server_templates",
    "system_status",
    "users",
]
